python amc_search.py \
    --job=train \
    --model=mobilenetv2 \
    --dataset=imagenet \
    --preserve_ratio=0.7 \
    --lbound=0.2 \
    --rbound=1 \
    --reward=acc_reward \
    --data_root=/ssd/dataset/imagenet \
    --ckpt_path=./checkpoints/mobilenetv2_imagenet.pth.tar \
    --seed=2018